BF: subclass numpy distutils build command
The ``get_comrec_build`` function returns a ``build_py`` object, but, by
default, subclasses from raw distutils.  We're using numpy distutils so
we need to subclass from numpy.distutils' version of ``build_py``.

Before this fix, when running ``python setup.py sdist``, we were getting
obscure errors ending in::

    AttributeError: 'tuple' object has no attribute 'split'