python2.5: Do not use relative import *
relative imports are not yet fully functional on python2.5, thus it would lead to

Compiling /usr/lib/pymodules/python2.5/nipy/algorithms/registration/__init__.py ...
  File "/usr/lib/pymodules/python2.5/nipy/algorithms/registration/__init__.py", line 3
    from .resample import *
SyntaxError: 'import *' not allowed with 'from .'

Compiling /usr/lib/pymodules/python2.5/nipy/neurospin/group/tests/test_mixed_effects.py ...
  File "/usr/lib/pymodules/python2.5/nipy/neurospin/group/tests/test_mixed_effects.py", line 4
    from ..mixed_effects import *
SyntaxError: 'import *' not allowed with 'from .'

in this patch replacing with absolute path for .. and simply removing . for
current submodule imports